### ISSUE TITLE
Agriculture AI isn't working in designdev branch 

### ISSUE THREAD

**Issue by saishinkar2** [dhdhagai/agriculturemonitoring#9]
After the recent design changes implemented in another branch of the repository, the agriculture AI feature has become non-functional, likely due to alterations in the underlying logic or integrations that support its operation, resulting in errors or unexpected behavior for users. Additionally, there is a problem with the "Send" button on the page, which may be unresponsive, failing to submit data, or lacking feedback for the user, potentially due to changes in its styling or positioning. To address these issues, it is essential to review the recent changes, debug the affected functionalities, conduct thorough testing to replicate the problems, and communicate findings with the development team to determine appropriate solutions, including the possibility of rolling back changes or implementing quick fixes while documenting the process for future reference.

Here's Screenshot for your reference
![Screenshot 2024-09-19 114017](https://github.com/user-attachments/assets/c537dd97-ec51-4f3e-922e-bcf0c643ce54)

Bugs
![image](https://github.com/user-attachments/assets/1ebfef52-cb22-435e-8d01-0a918982da0c)

**Comment by saishinkar2** [comment]
Minor changes remaining for this page and nav bar issues and send button orientation

**Comment by dhdhagai** [comment]
Fixed with the latest commit
